### ISSUE TITLE
Question / Feature Request: Humidity from Thermostat

### ISSUE THREAD

**Issue by ShooterQ** [natekspencer/hacs-vivint#104]
Hello, integration has worked great for me so far to integrate window, door, and motion sensors. I also have control of, and readings from, my thermostat save for the humidity. Any chance that I can do something to expose it? It could simply be because I have the older CT100 model.

![image](https://user-images.githubusercontent.com/37904834/232940907-f98457da-61f1-403b-b8a9-28fedddd6768.png)

![image](https://user-images.githubusercontent.com/37904834/232941013-bcc01c4c-580f-42ce-a960-d90df5dc10c8.png)

Comparison to a thermostat emulation where I do have humidity available:

![image](https://user-images.githubusercontent.com/37904834/232941072-79dc2c23-eb32-4151-9098-0f184c3d8832.png)

**Comment by natekspencer** [comment]
The humidity value should be exposed if it has it where expected. I don't have a CT100 to test/investigate, so if it does exist, you'll need to enable debugging and see if you can find the value. It's expected to be in a field titled `hmdt`.

Can you see humidity in the Vivint app for that device?

**Comment by ShooterQ** [comment]
> Can you see humidity in the Vivint app for that device?

Ha, I haven't used the Vivint app in so long that I didn't even think to check. Sure enough, it does not show up on the Vivint app, so I assume it's just not going to come in. The only place where the humidity value is displayed for the CT100 is on the physical device itself.
