### ISSUE TITLE
Latest HA update broke Vivint

### ISSUE THREAD

**Issue by oricalworks** [natekspencer/hacs-vivint#105]
Logger: homeassistant.setup
Source: setup.py:213 
First occurred: 10:07:54 PM (1 occurrences) 
Last logged: 10:07:54 PM

Setup failed for custom integration vivint: Unable to import component: cannot import name 'VivintDevice' from 'vivintpy.devices' (/usr/local/lib/python3.10/site-packages/vivintpy/devices/__init__.py)

Logger: homeassistant.components.automation
Source: components/automation/config.py:207 
Integration: Automation (documentation, issues) 
First occurred: 10:07:54 PM (2 occurrences) 
Last logged: 10:07:54 PM

Automation with alias 'DoorBell' failed to setup triggers and has been disabled: Integration 'vivint' does not support device automation triggers
Automation with alias 'auto unlock' failed to setup actions and has been disabled: Integration 'vivint' does not support device automation triggers

**Comment by natekspencer** [comment]
Make sure you are using the latest version of this integration as well. I have the latest non beta release of HA and don't have any issues with my device triggers.

**Comment by oricalworks** [comment]
> Make sure you are using the latest version of this integration as well. I have the latest non beta release of HA and don't have any issues with my device triggers.

After uninstall vivint from hacs and HA and reinstall 

Config flow could not be loaded: {"message":"Invalid handler specified"}

not too sure whats going on

**Comment by natekspencer** [comment]
Can you enable debugging and check your debug logs as well for any errors?

**Comment by oricalworks** [comment]
sure will do

**Comment by oricalworks** [comment]
How do I enable debugging?
