### ISSUE TITLE
Derive RTSP Stream of existing Vivint cameras for other add-ons like Frigate

### ISSUE THREAD

**Issue by thelightningist** [natekspencer/hacs-vivint#11]
I was able to get this integration working wonderfully but wanted to try and take it a step further. I was curious about feeding the added camera entity's RTSP stream into frigate via their configuration file. However, I am unable to determine what the RTSP stream URL is of the existing entities (for example, camera.doorbell entity) [in order to add them into Frigate.](https://blakeblackshear.github.io/frigate/configuration/cameras/) 

These clearly are added as RTSP streams already and I can view them in Lovelace. Is there some sort of simple method to find this information so that I can add these cameras into frigate?

**Comment by apercrcl01** [comment]
I am interested in this as well.

**Comment by DarellAdams** [comment]
I was trying to write a python script to extract the RTSP url from the panel but the API broke after Vivint had their maintenance, I'm hoping they fix it soon so I can share with you guys

**Comment by natekspencer** [comment]
It wouldn't be hard to expose this at all. If I recall, I even exposed it at one point in my initial iteration of the component as an attribute on the camera, but then decided to remove it from the published file because it could be a security issue (especially for external sources). But this section https://github.com/natekspencer/hacs-vivint/blob/a189ea2fc289db464f6ebc112e5d211091ad5556/custom_components/vivint/camera.py#L78 is where you would get the stream source, which is the RTSP url.

**Comment by thelightningist** [comment]
Hi @DarellAdams 

Thanks so much for sharing your script! Just so I understand this correctly, where exactly do you place the cameraRTSP script at? The vivint folder under custom_componets?

**Comment by DarellAdams** [comment]
@thelightningist 
Sorry for the late reply. You actually need to run this on a laptop/client computer.

1. On your Mac/PC, run a terminal, cmd, or powershell
2. Make sure you have python3 installed (Just google it to install)
3. Make sure module vivintpy is installed (_install vivintpy module: **pip install vivintpy**_)
4. On terminal, cd /path/of/the/scirpt/ (e.i **cd C:\Scripts**)
5. C:\Scripts> python3 camRTSP.py [username] [password]

**Comment by natekspencer** [comment]
I just released version 2021.9.5 that includes the ability to enable logging of the rtsp urls via the configure option on the integration. Please note that you also have to have logging enabled in your configuration.yaml file with `custom_components.vivint` set to a minimum of `info`. Here's an example:

```yaml
logger:
  default: error
  logs:
    custom_components.vivint: info
```

**Comment by thelightningist** [comment]
Awesome! Thanks so much!

**Comment by forrestrose** [comment]
Do you need to have the cameras connected to the vivint panel after adding to frigate?
