### ISSUE TITLE
Camera as Speaker 

### ISSUE THREAD

**Issue by mishugashu** [natekspencer/hacs-vivint#111]
I noticed that the outdoor cameras have speakers. I was thinking I could use it as a media player, but I cannot see the device as a speaker, only a camera. Would this feature be possible? Thank you.

**Comment by natekspencer** [comment]
I haven't figured out how to send audio to the cameras and admittedly it's very low on my list of priorities. Someone else will likely have to tackle it and then I'd be happy to integrate it.
