### ISSUE TITLE
Vivint Integration Broken after update 2023.8.0

### ISSUE THREAD

**Issue by rereloluwa89** [natekspencer/hacs-vivint#112]
After update home assistant flags the vivint devices as "invalid" and they do let load; the entities pull in fine but now I have no devices that I can automate or interact with, just entities- can you help?

**Comment by natekspencer** [comment]
Can you enable debug logs and post any relevant information from it? Right now, it's difficult for me to guess what the issue is and I haven't updated to 2023.8 yet myself.

**Comment by rereloluwa89** [comment]
i can attach the full log if you want, thank you so much for your quick response
