### ISSUE TITLE
2023.8.1 - Hub shows as unavailable

### ISSUE THREAD

**Issue by rereloluwa89** [natekspencer/hacs-vivint#115]
Just installed 2023.8.1

Only one entity doesn't work/load - the hub. It shows as unavailable, so i can't arm/disarm. 
Cameras and sensors appear to work fine

![image](https://github.com/natekspencer/hacs-vivint/assets/138394359/8fdbb5bf-d4e6-4efe-b8f1-97bb17fd398d)

**Comment by rereloluwa89** [comment]
Also, my current version: Home Assistant 2023.8.2

**Comment by natekspencer** [comment]
Can you see/post if there are any errors in your logs?

**Comment by rereloluwa89** [comment]
Logger: homeassistant.helpers.service
Source: helpers/service.py:833
First occurred: 8:39:01 AM (2 occurrences)
Last logged: 9:43:08 AM

Referenced entities alarm_control_panel.ayeni_home are missing or not currently available

**Comment by rereloluwa89** [comment]
Log Details (ERROR)
Logger: homeassistant.config_entries
Source: config_entries.py:1367
First occurred: 1:49:49 AM (1 occurrences)
Last logged: 1:49:49 AM

Error setting up entry rereloluwaa@gmail.com for vivint
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 388, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/vivint/__init__.py", line 123, in async_setup_entry
    await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1367, in async_forward_entry_setups
    await asyncio.gather(
asyncio.exceptions.CancelledError

**Comment by natekspencer** [comment]
Thanks, that helps. It looks like it's just a timeout issue. If you reload the integration, you should probably get it back unless it happens again. I do see some code I can adjust though to prevent it from trying to re-update right away which is what is leading to this issue.

**Comment by rereloluwa89** [comment]
ok, i'll give that a try, thanks

**Comment by natekspencer** [comment]
I did also release a new version to avoid an extra call to help with this

**Comment by rereloluwa89** [comment]
oh ok, yeah i didn't have luck reloading. i'll download the new version

**Comment by rereloluwa89** [comment]
upon install of update and after restarting, i can't seem to configure the integration:

i get an unknown error occurred window:

![image](https://github.com/natekspencer/hacs-vivint/assets/138394359/d60f8b30-f8a3-4a32-8f92-b1f730bbb71b)

**Comment by rereloluwa89** [comment]
log:

Logger: homeassistant.components.http.ban
Source: components/http/ban.py:82
Integration: HTTP (documentation, issues)
First occurred: 1:59:03 PM (1 occurrences)
Last logged: 1:59:03 PM

Login attempt or request with invalid authentication from localhost (127.0.0.1). Requested URL: '/api/config/config_entries/flow/cb5fe1987f871171a2b01baecbcd62c9'. (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36)

**Comment by rereloluwa89** [comment]
is this a function of trying to install via nabu casa? (i'm at work/logged in remotely)?

**Comment by natekspencer** [comment]
Yeah that error seems unrelated to this integration

**Comment by rereloluwa89** [comment]
oh ok
