### ISSUE TITLE
Doorbell Camera Delay

### ISSUE THREAD

**Issue by j0np** [natekspencer/hacs-vivint#120]
### The problem

I have 2 cameras, one is on lan and no issues, however my doorbell camera which is on wifi seems to have about 5 second delay. Currently turned off HD and set to direct, any other custom settings that is available to fine tune the stream to make it more real time?

### What version of Home Assistant Core are you running?

core-2023.11.1

**Comment by natekspencer** [comment]
Unfortunately there are not.
