### ISSUE TITLE
Cameras connected via POE switch not loading anymore

### ISSUE THREAD

**Issue by awss12312** [natekspencer/hacs-vivint#124]
### The problem

Issue seems to have started within the past few months. All POE cameras show as “connected” but “unavailable”. Issue is not affected WiFi cameras and cameras connected via wireless POE bridge

### What version of Home Assistant Core are you running?

core-2023.10.1

**Comment by natekspencer** [comment]
Can you share a screenshot and turn on debugging to see if there are any errors in the logs? And these cameras were working before? I'm having issues lately with my PoE cameras as well, but not the same you seem to be referring to. Mine are connected, but the stream doesn't seem to connect as well as it used to for PoE cameras.

**Comment by awss12312** [comment]
![IMG_0110](https://github.com/natekspencer/hacs-vivint/assets/133473845/e2986d52-7d13-47ad-b182-5c1077ddd8eb)
![IMG_0111](https://github.com/natekspencer/hacs-vivint/assets/133473845/9ab7f51c-3dce-4a1f-a885-980216e612d0)

**Comment by natekspencer** [comment]
Are the other motion sensors or toggles also unavailable or can you control them? Unfortunately, this just uses the RTSP stream and there isn't anything I'm aware of outside of that to enable video in HA.

**Comment by awss12312** [comment]
Turned on debugging and these are the errors I see:

Logger: homeassistant.components.stream.stream.camera.backyard
Source: components/stream/__init__.py:431
Integration: Stream (documentation, issues)
First occurred: 6:49:42 AM (104 occurrences)
Last logged: 9:42:53 PM

Error from stream worker: Error opening stream (INVALIDDATA, Invalid data found when processing input) rtsp://****:****@192.168.1.249:554/stream1,audio=opus

Logger: homeassistant.components.stream.stream.camera.front_yard
Source: components/stream/__init__.py:431
Integration: Stream (documentation, issues)
First occurred: 9:48:53 PM (5 occurrences)
Last logged: 9:50:33 PM

Error from stream worker: Error opening stream (INVALIDDATA, Invalid data found when processing input) rtsp://****:****@192.168.1.97:554/stream1,audio=opus
