### ISSUE TITLE
Connection to Vivint seems to be throttled or delayed

### ISSUE THREAD

**Issue by Alexithemia** [natekspencer/hacs-vivint#129]
### The problem

Not sure when it started, maybe since the last homeassistant core update, but vivint commands seem heavily delayed, by sometimes 10 minutes. I tried reloading and reinstalling the integration, and relogging into my vivint account, no changes. Initializing the integration takes almost 10 minutes as well. All the commands eventually go through, but very delayed.

Doing the same things through the Vivint App on my phone are instant.
Doing other things with Home Assistant are instant - like turning on off lights (Homekit - leviton), or washer/dryer commands (HACS - SmartThinQ LGE Sensors)

### What version of Home Assistant Core are you running?

core-2024.2.1

**Comment by natekspencer** [comment]
Can you enable logging and post those? My system is functioning immediately still.

**Comment by Alexithemia** [comment]
I'm going to go ahead and close this, in the logs it was giving a weird timeout error trying to download your readme repeatedly. I just completely removed the integration and reinstalled it and things are working fine now

**Comment by Alexithemia** [comment]
Actually I'm having this issue again now. This is all I get from the logs of it

`This error originated from a custom integration.

Logger: custom_components.hacs
Source: custom_components/hacs/base.py:734
Integration: HACS (documentation, issues)
First occurred: February 22, 2024 at 12:11:10 AM (5 occurrences)
Last logged: February 22, 2024 at 12:15:18 AM

A timeout of 60! seconds was encountered while downloading https://raw.githubusercontent.com/natekspencer/hacs-vivint/2023.12.0/README.md, using over 60 seconds to download a single file is not normal. This is not a problem with HACS but how your host communicates with GitHub. Retrying up to 5 times to mask/hide your host/network problems to stop the flow of issues opened about it. Tries left 4
A timeout of 60! seconds was encountered while downloading https://raw.githubusercontent.com/natekspencer/hacs-vivint/2023.12.0/README.md, using over 60 seconds to download a single file is not normal. This is not a problem with HACS but how your host communicates with GitHub. Retrying up to 5 times to mask/hide your host/network problems to stop the flow of issues opened about it. Tries left 3
A timeout of 60! seconds was encountered while downloading https://raw.githubusercontent.com/natekspencer/hacs-vivint/2023.12.0/README.md, using over 60 seconds to download a single file is not normal. This is not a problem with HACS but how your host communicates with GitHub. Retrying up to 5 times to mask/hide your host/network problems to stop the flow of issues opened about it. Tries left 2
A timeout of 60! seconds was encountered while downloading https://raw.githubusercontent.com/natekspencer/hacs-vivint/2023.12.0/README.md, using over 60 seconds to download a single file is not normal. This is not a problem with HACS but how your host communicates with GitHub. Retrying up to 5 times to mask/hide your host/network problems to stop the flow of issues opened about it. Tries left 1
A timeout of 60! seconds was encountered while downloading https://raw.githubusercontent.com/natekspencer/hacs-vivint/2023.12.0/README.md, using over 60 seconds to download a single file is not normal. This is not a problem with HACS but how your host communicates with GitHub. Retrying up to 5 times to mask/hide your host/network problems to stop the flow of issues opened about it. Tries left 0`

**Comment by natekspencer** [comment]
This is an error with your computer and GitHub and not the integration.

**Comment by Alexithemia** [comment]
Sorry for bothering you with the issues then, do you happen to know how I can resolve this? Do I need to log into GitHub within HACS or something?

**Comment by natekspencer** [comment]
Maybe try some of the things from this community post: https://community.home-assistant.io/t/just-installed-hacs-unable-to-download-anything-due-to-forever-loading/375834/9
