### ISSUE TITLE
Cameras always idle or unavailable on any setting

### ISSUE THREAD

**Issue by SLYtiger16** [natekspencer/hacs-vivint#138]
### The problem

I installed yesterday, the cameras are identified but the picture is always a broken image icon and remains "idle" or "unavailable" at all times. 
Switched between 'Direct', 'Indirect', and even tried external. With or without HD. 

### What version of Home Assistant Core are you running?

2024.5.3

### What was the last working version of Home Assistant Core?

NA

### Anything in the logs that might be useful?

```txt
2024-05-13 08:09:10.723 ERROR (MainThread) [homeassistant.helpers.entity_registry] 'alarm_control_panel' from integration vivint has a non string unique_id '9999999999', please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+vivint%22

****Replaced numerical value with 9's
```

### Additional information

I have streaming on one camera and it repeatedly has a host unreachable error, although I suspect it is related to the main error.

**Comment by n8henrie** [comment]
Same here. Camera stream previously was working but then I haven't checked in several months and now no longer works. Pulled the latest changes from this repo and hass, tried all config options, no luck.

**Comment by SLYtiger16** [comment]
I ended up getting the newer cameras and they work fine. It's the old camera version being phased out by vivint I believe.
________________________________
