### ISSUE TITLE
Hue Lights

### ISSUE THREAD

**Issue by Ratoka** [natekspencer/hacs-vivint#139]
### The problem

After configuring the integration, I have had my Hue lights show up in the Vivint panel.  I can remove the lights by contacting support to enable installer mode, then pairing/removing the hue bridge, but the lights show up between 1-24 hours after the bridge is added/removed.  Is the integration capable of doing this?  If so, is there a way to prevent devices from zha from being seen by the panel?

### What version of Home Assistant Core are you running?

core-2024.5.5

### Additional information

The account I am using to integrate is dedicated and is not configured with admin rights.

**Comment by natekspencer** [comment]
The integration is not able to do this.

**Comment by Ratoka** [comment]
Thank you, Nate.  I will continue to troubleshoot with Vivint.
