### ISSUE TITLE
Vivint integration no longer authenticates with MFA

### ISSUE THREAD

**Issue by jvonhoff** [natekspencer/hacs-vivint#142]
### The problem

After the upgrade to 2024.8.0, my Vivint integration asked me to reconfirm my MFA code.  I input the correct code, but it times out with an "Unexpected error".  Repeat this 3-4 more times, including deleting the Vivint integration & setting it up anew.

I did confirm that I am able to log in (with MFA) on the official Vivint Android app, but the same MFA token does not appear to work with the integration.

As I deleted & re-installed the integration, the only debug log I have captured is below:

```
This error originated from a custom integration.

Logger: custom_components.vivint.config_flow
Source: custom_components/vivint/config_flow.py:168
integration: Vivint (documentation, issues)
First occurred: 1:41:31 PM (2 occurrences)
Last logged: 2:18:54 PM

500, message='Internal Server Error', url=URL('https://www.vivintsky.com/platform-user-api/v0/platformusers/2fa/validate')
503, message='Service Unavailable', url=URL('https://www.vivintsky.com/platform-user-api/v0/platformusers/2fa/validate')
```

### What version of Home Assistant Core are you running?

core-2024.8.0

### What was the last working version of Home Assistant Core?

core-2024.7.4

**Comment by natekspencer** [comment]
So it looks like it no longer works if you have MFA via a device (authenticator/authy/etc). But if you have it enabled via SMS/email, it still works. I'm not sure when I'll be able to get a fix in

**Comment by jvonhoff** [comment]
Thanks for that info.  I switched off 2FA via the Android app, and then, when I tried to log in again (2FA still disabled in the app) it sent me a text with a code that allowed Home Assistant to connect.  However, when I went to re-enable 2FA, it doesn't think that Keepass is a valid 2FA app, so it wouldn't let me proceed to enable 2FA again.

So, Vivint is back functional in Home Assistant (WITH MY THANKS!) and my Vivint app appears to be using SMS 2FA, even with the 2FA switched off.

Unless you think otherwise, I'll leave this open until we can get device-based 2FA to work the way it was.  We may be waiting on Vivint to update the app again, though?

**Comment by natekspencer** [comment]
Yeah, let's keep it open for now as I anticipate others will run into this issue in the interim.

**Comment by Daedilus** [comment]
I've tried to follow Tuxrug's example, but to no avail. Please let me know if you want any debug logs as another example.

**Comment by norimicry** [comment]
+1 for having to delete and reinstall the entire integration for SMS MFA to work.

**Comment by Daedilus** [comment]
> +1 for having to delete and reinstall the entire integration for SMS MFA to work.

Did you have to remove from hacs as well?

**Comment by norimicry** [comment]
> Did you have to remove from hacs as well?

No, just deleting the integration from the integrations menu and set it up as a new integration.

**Comment by trek-boldly-go** [comment]
I am still on 2024.7.3 and my authentication has "expired" twice in the last two days. I already had 2FA disabled, but it randomly disconnected last night at 2 AM and send me 2 MFA codes via SMS back to back. Of course, I was asleep so I couldn't type in the codes within the 5 minute validity window, and I couldn't figure out how to retrigger the auth workflow (an integration restart didn't work, neither did disabling and reenabling it). I didn't want to reboot my HA, so deleting the integration config and adding it back worked. Hopefully 🤞 it doesn't sign me out again.

**Comment by Daedilus** [comment]
>  I didn't want to reboot my HA, so deleting the integration config and adding it back worked. Hopefully 🤞 it doesn't sign me out again.

Removing and re-adding mine still gets me stuck at the MFA. It just times out.

**Comment by norimicry** [comment]
> Removing and re-adding mine still gets me stuck at the MFA. It just times out.

Did you remove the Authenticator MFA? It has to be the SMS MFA, which is enabled by default when you remove your Authenticator. Removing that and reinstalling the integration is what fixed it for me.

**Comment by Tuxrug** [comment]
> I am still on 2024.7.3 and my authentication has "expired" twice in the last two days. I already had 2FA disabled, but it randomly disconnected last night at 2 AM and send me 2 MFA codes via SMS back to back. Of course, I was asleep so I couldn't type in the codes within the 5 minute validity window, and I couldn't figure out how to retrigger the auth workflow (an integration restart didn't work, neither did disabling and reenabling it). I didn't want to reboot my HA, so deleting the integration config and adding it back worked. Hopefully 🤞 it doesn't sign me out again.

So far my authentication only expired when I went from 2024.7.4 to 2024.8.0, and it did it both times I tested that transition (rollback, reauth, re-update docker image). But it did not expire today when I updated from 2024.8.0 to 2024.8.1.

**Comment by blakenorthrup** [comment]
> Thanks for that info. I switched off 2FA via the Android app, and then, when I tried to log in again (2FA still disabled in the app) it sent me a text with a code that allowed Home Assistant to connect. However, when I went to re-enable 2FA, it doesn't think that Keepass is a valid 2FA app, so it wouldn't let me proceed to enable 2FA again.
> 
> So, Vivint is back functional in Home Assistant (WITH MY THANKS!) and my Vivint app appears to be using SMS 2FA, even with the 2FA switched off.
> 
> Unless you think otherwise, I'll leave this open until we can get device-based 2FA to work the way it was. We may be waiting on Vivint to update the app again, though?

You are the man! Much appreciate the fix!

**Comment by jvonhoff** [comment]
> You are the man! Much appreciate the fix!

All the credit for fixes goes to @natekspencer  but, I'm happy I could help with a workaround!  Cheers!

**Comment by ndoty** [comment]
I dsiabled 2fa in the app and tried to reconfigure the integration and i get none when typing in the SMS code i get.  Core: 2024.8.2, HACS: 1.34.0, Vivint Integration: 2024.7.0. I am unable to get the integration to work at all right now.

**Comment by Tuxrug** [comment]
> I dsiabled 2fa in the app and tried to reconfigure the integration and i get none when typing in the SMS code i get.  Core: 2024.8.2, HACS: 1.34.0, Vivint Integration: 2024.7.0. I am unable to get the integration to work at all right now.

Remove the integration and re-add it, that's what I had to do to get it to reauthenticate.

**Comment by matthewmattern** [comment]
I have tried disabling 2FA in Vivint APP and setting up notification forwarding, but I never get an SMS code, not sure what if anything I am doing wrong.  Vivint integration now says unknown error after asking for MFA Code.  Plus I can't see to find where to delete the integration.  Freaking Vivint, I also had to delete all my ZWave Switches as now their panel will only support 10 Zwaves devices.  any help would be appreciated thank you

**Comment by fxfitz** [comment]
Seeing the same issue!

I've always used SMS 2FA. While I've always been able to get it to work by reloading the integration, getting the text with the code, can putting the code into the integration, recently (within the last few days) I don't think it has ever really successfully logged back in. I always have the "error authenticating" repair notification.

**Comment by n8henrie** [comment]
Another TOTP MFA user getting the same error as above.

FWIW, I'm seeing a 500 error in the hass logs when accessing https://www.vivintsky.com/platform-user-api/v0/platformusers/2fa/validate

**Comment by n8henrie** [comment]
Assuming perhaps some backend endpoints have changed.

No expert with this tool, but running mitmproxy on the iOS app and doing a logout / login, I see the following request:

POST https://id.vivint.com/idp/api/submit?client_id=ios
Referer:          https://id.vivint.com/idp/totp  

```json
{"mfa":"123456","password":"hunter2","username":"n8henrie@fake.com"}
```

Don't have time to keep digging today, but thought this might be helpful.

**Comment by ndoty** [comment]
Any update on this? Removing the integration and re-adding once SMS 2fa is enabled is a workaround.

**Comment by natekspencer** [comment]
This should be resolved in 2024.10.0.

**Comment by ndoty** [comment]
> This should be resolved in 2024.10.0.

Thanks Nate. the work around has been okay but the fix is certainly welcomed!

**Comment by natekspencer** [comment]
I pulled the 2024.10.0 release, there seems to be some funkiness with the refresh_token that I didn't experience while developing.

**Comment by natekspencer** [comment]
Release 2024.10.1 should fix this now.
