### ISSUE TITLE
With latest update, no longer works when not using MFA.

### ISSUE THREAD

**Issue by jrschat** [natekspencer/hacs-vivint#145]
### The problem

I do not use MFA with the native Vivint App. With the latest release of your integration, the integration is unable to authenticate without a MFA code. Was the intent to force users to use MFA?

I am able to force thru the generation of a OTP for MFA and log in again but this is highly inconvenient to do upon each restart of HA.

Are you able to re-enable the ability to not use MFA?

### What version of Home Assistant Core are you running?

core-2024.10.1

### What was the last working version of Home Assistant Core?

core-2024.10.1

### Anything in the logs that might be useful?

```txt
This error originated from a custom integration.

Logger: custom_components.vivint.hub
Source: custom_components/vivint/hub.py:109
integration: Vivint (documentation, issues)
First occurred: 12:22:49 (2 occurrences)
Last logged: 12:22:50

Invalid credentials

Logger: homeassistant.config_entries
Source: config_entries.py:622
First occurred: 12:22:49 (1 occurrences)
Last logged: 12:22:49

Config entry 'Battle Net' for vivint integration could not authenticate: invalid_grant
```

**Comment by natekspencer** [comment]
My understanding is Vivint always requires a second code at this point. This is either via email/sms or an authenticator app. That being said, you shouldn't need to do this on each restart as it now saves a refresh token that can be used to initiate the new session on restart.

**Comment by jrschat** [comment]
Until installing today's release of your integration I have never had to use a MFA token to login on any device. I just logged out and back into the native app on my phone and was not prompted for a MFA token.

A reload of the integration or the global yaml config does not require re-authentication but upon a restart of HA authentication is flagged as expired and I must login again with both username/password and a MFA token.

Maybe it is a change that all API sessions require a MFA token.

**Comment by natekspencer** [comment]
I pulled the 2024.10.0 release, there seems to be some funkiness with the refresh_token that I didn't experience while developing.

**Comment by jrschat** [comment]
Sucks that the behavior is different. I am glad I said something now. It was also interesting as the device that represents the panel was created as a new device and the old was left in place as unavailable.

**Comment by natekspencer** [comment]
@jrschat I released a beta version that seems to be working for me across multiple restarts now. [2024.10.1b1](https://github.com/natekspencer/hacs-vivint/releases/tag/2024.10.1b1).

I added some additional logging around the MFA requirement. Right now, the only accounts I have come back and tell me that I need an MFA/SMS code. It is possible that it is not required on some accounts, such as yours, but I don't know what that response looks like. If it's possible for you to install this beta, enable debug logging, and attempt a sign in, I might be able to see if there is a response that states MFA is not needed and not require it.

**Comment by jrschat** [comment]
[home-assistant_vivint_2024-10-09_edited.log](https://github.com/user-attachments/files/17311062/home-assistant_vivint_2024-10-09_edited.log)

I remove the addresses for the camera feeds but otherwise left it alone. I installed, restarted, enabled debug logging, signed in, used the MFA token it emailed, and then stopped logging.

**Comment by natekspencer** [comment]
Thanks @jrschat, that looks like what I expected and shows the SMS code is required. I know you said when you login with that account on the app it doesn't ask for a code. Could you try a private browsing session and login at vivint.com to see if it forces a code?

**Comment by jrschat** [comment]
@natekspencer, interestingly enough if I login using a private browsing session it does prompt me for the MFA token. If I login using a non private browsing session it does not prompt.

**Comment by natekspencer** [comment]
Thanks, that confirms what I saw when doing some testing. After logging in, Vivint sets some cookies in the session. If those don't get cleared, when you attempt to login again, it can re-use those cookies and skip MFA.

**Comment by jrschat** [comment]
Ok, so it sounds like the new norm is going to be login with a token upon every restart. I am now curious if the homebridge plugin has the same new limitation. It did not prior to to me migrating to HA. I remember they went through a phase figuring it out because it was broken for awhile  prior to the migration.

**Comment by natekspencer** [comment]
You shouldn't need an MFA on every restart. The code attempts to save the refresh token and use that when loading initially. If it's expired, it will require a new token though. Are you still seeing that issue of needing to authenticate on every restart?

**Comment by jrschat** [comment]
Well curiosity got the best of me, the homebridge plugin did not require me to enter a MFA token.

**Comment by jrschat** [comment]
I had not restarted again yet. I just did a single restart and now the MFA upon restart did not occur. I did not realize you had changed anything else besides the logging changes.

**Comment by natekspencer** [comment]
Yeah, sorry. There was a race condition in the previous release that almost always happened in production but very very rarely while debugging that prevented saving the token.

**Comment by natekspencer** [comment]
> Well curiosity got the best of me, the homebridge plugin did not require me to enter a MFA token.

I'm not really sure how homebridge works, but If homebridge uses the same browser, it is picking up those cookies.

**Comment by jrschat** [comment]
I am going to close this now because having to generate a token once in awhile is not a super big deal.

Thanks for taking a look at it.
