### ISSUE TITLE
Failed to connect

### ISSUE THREAD

**Issue by matwatson123** [natekspencer/hacs-vivint#15]
First time user here.  When I attempt to add the integration, it first goes to a box for me to add user name and password but I get the message "Failed to connect".  I know it's not a password issue I validated to the Vivint website and my local login.  Any ideas?

**Comment by natekspencer** [comment]
@matwatson123 are you still seeing this issue? If so, which panel do you have, what version of Home Assistant and this Vivint integration are you using?

**Comment by matwatson123** [comment]
It seems to be working now. Maybe it was related to the other outage stuff going on. Thanks for checking in bruv!
