### ISSUE TITLE
Integration will not load 

### ISSUE THREAD

**Issue by droolingtaz** [natekspencer/hacs-vivint#151]
### The problem

I just upgraded to HA 2024.11.0b0 beta and the integration will no longer load

### What version of Home Assistant Core are you running?

2024.11.0b0

### What was the last working version of Home Assistant Core?

2024.10.4

### Anything in the logs that might be useful?

```txt
Logger: homeassistant.util.package
Source: util/package.py:152
First occurred: 7:25:37 PM (3 occurrences)
Last logged: 7:25:41 PM

Unable to install package vivintpy==2024.1.1: × No solution found when resolving dependencies: ╰─▶ Because vivintpy==2024.1.1 depends on protobuf>=4.23.1,<5.0.0 and protobuf==5.28.3, we can conclude that vivintpy==2024.1.1 cannot be used. And because you require vivintpy==2024.1.1, we can conclude that your requirements are unsatisfiable.
```

**Comment by eosho** [comment]
+1. Reverted back to a back up

**Comment by trek-boldly-go** [comment]
Same problem, going to restore from a backup now.

**Comment by natekspencer** [comment]
[2024.11.0](https://github.com/natekspencer/hacs-vivint/releases/tag/2024.11.0) should resolve the dependencies issue

**Comment by droolingtaz** [comment]
When trying to install it says it requires HA 2024.11.0 but I have 2024.11.0b1 installed Sent from my iPhoneOn Nov 1, 2024, at 6:12 PM, Nathan Spencer ***@***.***> wrote:﻿
Closed #151 as completed via #152.

**Comment by natekspencer** [comment]
Please install 2024.11.0, not 2024.11.1

Thank you

**Comment by droolingtaz** [comment]
Spot on.  Thank you so much Sent from my iPhoneOn Nov 1, 2024, at 11:08 PM, Nathan Spencer ***@***.***> wrote:﻿
Please install 2024.11.0, not 2024.11.1
Thank you
