### ISSUE TITLE
The camera entity [entity] does not support requesting width and height, please open an issue with the integration author

### ISSUE THREAD

**Issue by mat1583** [natekspencer/hacs-vivint#19]
I see this warning in the logs occasionally. I haven't been able to replicate it reliably, and it's probably not a true issue, but I wanted to go ahead and submit it in case anyone else has seen it (or if it does need to be fixed). 

Logger: homeassistant.components.camera
Source: components/camera/__init__.py:466
Integration: Camera (documentation, issues)
First occurred: 9:15:24 AM (2 occurrences)
Last logged: 9:15:24 AM

The camera entity camera.doorbell does not support requesting width and height, please open an issue with the integration author
The camera entity camera.driveway_camera does not support requesting width and height, please open an issue with the integration author

**Comment by kitprice** [comment]
This was a breaking change in [2019.9.0](https://github.com/home-assistant/core/pull/53835).  Need to update function singature for _async_camera_image_ to match.

**Comment by natekspencer** [comment]
Fixed in 2021.10.1
