### ISSUE TITLE
Username/password?

### ISSUE THREAD

**Issue by ksignorini** [natekspencer/hacs-vivint#22]
Upon setup, I'm asked for my Vivint username/password.

Which username/password is this?

**Comment by natekspencer** [comment]
This should be the same username/password you use to login on the app and/or website.

**Comment by ksignorini** [comment]
Hmmm. I'll try again.

**Comment by ksignorini** [comment]
Looks like it might have been my firewall. I'd like to test again but can't find a way to log out of the integration.

**Comment by natekspencer** [comment]
You just need to delete the integration and then add a new one.

**Comment by ksignorini** [comment]
Ah. Thanks. I'll post back here one more time before you close the ticket re: firewall for future reference.

**Comment by ksignorini** [comment]
Nope. Wasn't firewall. Just started to work now. Feel free to close this ticket. Thanks!

**Comment by natekspencer** [comment]
Just as an fyi, you should be able to close your own tickets.
