### ISSUE TITLE
One device not integrating

### ISSUE THREAD

**Issue by ksignorini** [natekspencer/hacs-vivint#23]
This is working GREAT!!!

The only thing is, my Front Door does not appear as a device in the integration devices list. All my other devices, including another door, do show up.

The Front Door exists in the panel devices as well as in the Vivint app (available for automations in the app).

Ideas?

**Comment by ksignorini** [comment]
I can add that it's a wired device wired straight into the panel (I remember that from install a few years ago and it's right beside the panel).

**Comment by ksignorini** [comment]
For further information, this device does show up in the Vivint panel devices but does not show up in the Vivint _app_ device list. Very strange.

**Comment by natekspencer** [comment]
This uses the same API as the app, so if it's not in the app, then it's probably not exposed from the panel.

**Comment by ksignorini** [comment]
I've worked this out with Vivint. It's apparently because of how they physically integrated the existing point. It looks like they can't expose it. (They're sending me a new sensor.) Feel free to close this.
