### ISSUE TITLE
Privacy Mode?

### ISSUE THREAD

**Issue by ksignorini** [natekspencer/hacs-vivint#24]
Is there any way to control the Privacy Mode of a Vivint indoor camera (Ping?) through the integration?

**Comment by natekspencer** [comment]
Currently there is not

**Comment by ksignorini** [comment]
OK. Thanks. Feel free to close.

**Comment by natekspencer** [comment]
I'll leave it open as a feature request for now.

**Comment by natekspencer** [comment]
This is available in [2023.3.2](https://github.com/natekspencer/hacs-vivint/releases/tag/2023.3.2)
