### ISSUE TITLE
One binary device backwards

### ISSUE THREAD

**Issue by ksignorini** [natekspencer/hacs-vivint#25]
I have a door switch that shows "closed" when close and "open" when open in Vivint. In Home assistant the point is backwards, showing "off" when closed and "on" when open (even the units are weird). I have another door switch of the same type in Vivint that correctly shows open and closed correctly after integrating in to HASS through this integration.

Ideas?

**Comment by ksignorini** [comment]
My mistake in that sensor #2 is not the same as sensor #1 that's showing up backwards from what it shows in Vivint. However, sensor #1 does show as on/off vs closed/open (backwards and with different units).

**Comment by natekspencer** [comment]
When sensors are added to the panel, they can be assigned a "type" such as door, window, contact, fire, etc. This integration reads that type and then assigns the corresponding device class to it in Home Assistant. So even though it might be named as a door, the API says it is something else and appears as such. You can modify the device class of the entity via the "customizations" section of Home Assistant to get it to use the appropriate open/close values.

**Comment by ksignorini** [comment]
I understand now. Thank you. I'll customize it on the HASS end.

**Comment by ksignorini** [comment]
Feel free to close.
