### ISSUE TITLE
Vivint thermostat humidity?

### ISSUE THREAD

**Issue by ksignorini** [natekspencer/hacs-vivint#26]
I can't seem to find a humidity entity for the Vivint thermostat. I can see that its data is being pulled in somehow when I look at the point in developer mode:

![image](https://user-images.githubusercontent.com/6867660/142784939-bf186059-08cb-47c2-a682-23254cf33045.png)

I see "current humidity" there and it matches what I see on my app.

I know very little about how HASS works in the back end, but I'm wondering if I'm just missing something in pulling in the humidity to display on a gauge, for example.

**Comment by ksignorini** [comment]
Nevermind. Apparently I was able to access that attribute in an entity card this time. Hm. Guess it works!

**Comment by natekspencer** [comment]
Entities in certain domains (such as [climate](https://developers.home-assistant.io/docs/core/entity/climate#properties)) have more attributes than others that can be read through various means in HA or optionally exposed as a separate entity.
