### ISSUE TITLE
Vivint camera feed fine on web but not mobile (doorbell cam)

### ISSUE THREAD

**Issue by ksignorini** [natekspencer/hacs-vivint#27]
My Vivint doorbell cam integrates well and its stream is visible and live in the HA web interface.

When viewing with mobile, only a black screen is shown--the feed does not come through. All other non-doorbell cameras work fine in mobile.

**Comment by natekspencer** [comment]
Have you selected "preload stream"? That could help with the issue on your mobile.

**Comment by ksignorini** [comment]
Yup. Out of nowhere it started working fine and now seems reliable. Thanks.
