### ISSUE TITLE
Issue with cameras not showing up in my feed but the motion sensors from the cameras are operational.  

### ISSUE THREAD

**Issue by Tomato-Lover666** [natekspencer/hacs-vivint#28]
I have been encountering " ERROR (stream_worker) [homeassistant.components.stream.worker] Error opening stream rtsp://****:****@***.***.***.***:8554/Video-50" and also the same error ending in /Video-40 for the other camera I am trying to set up.  

Still learning all of this but all of the HA and the rest of my vivint equipment is working really nice.  Thanks alot for all of your work! 

**I have gotten it all running. Thank you so much for this wonderful integration.

**Comment by natekspencer** [comment]
Yeah, I see that stream_worker error on mine occasionally, too. I think the issue is from the camera and/or stream component rather than from this integration itself.
