### ISSUE TITLE
Video Feed Enhancement/Question

### ISSUE THREAD

**Issue by kksligh** [natekspencer/hacs-vivint#33]
Is it possible to get sound through the video Feed in lovelace?

Is it possible to expose the two way communication options with the video Feed in lovelace? 

My guess is no but I've always wanted to ask.

**Comment by natekspencer** [comment]
Right now, no. The audio provided by the Vivint cameras is encoded with opus which is not natively supported by HA at this time. So the audio is already in the RTSP url, HA just can't play it yet.

**Comment by kksligh** [comment]
Got it, thanks!

**Comment by natekspencer** [comment]
@kksligh if you add this HACS component: https://github.com/AlexxIT/WebRTC, you can create a lovelace card with the following:
```yaml
type: custom:webrtc-camera
entity: camera.driveway_camera
```
which will pull in the video stream as well as the audio (tested and working on my instance)

**Comment by kksligh** [comment]
Awesome! I'll give it a try

Thanks,

Kale Sligh

VP, Marketing
o 615.744.1206
m 615.917.1441
________________________________
