### ISSUE TITLE
Vivint RTSP URL

### ISSUE THREAD

**Issue by jvwjgames** [natekspencer/hacs-vivint#34]
Where do i find the RTSP URL from a vivint camera i have it logging the RTSP URL but can't find it in logs. Thanks in advance.

**Comment by natekspencer** [comment]
You'll also need to enable the logger integration and set `custom_components.vivint` to either `debug` of `info`.

Please see these issues for more info:
https://github.com/natekspencer/hacs-vivint/issues/18
https://github.com/natekspencer/hacs-vivint/issues/11#issuecomment-923167696
