### ISSUE TITLE
Camera Motion Sensors Defaults To Unknown Instead of Clear (HA 2022.2)

### ISSUE THREAD

**Issue by garettharnish** [natekspencer/hacs-vivint#38]
![image](https://user-images.githubusercontent.com/11217208/152631835-a8d857da-8a90-44f0-85fc-d1d26b1cd1dd.png)

My Driveway Camera is no longer returning to clear when there is no motion; it is going to "Unknown" instead.   It is still detecting motion, but I'm not sure on/off are the modes it is using.   This is just affecting the camera motion detection; my actual vivint motion sensor is still clear/motion.

**Comment by Tuxrug** [comment]
Mine still shows when motion is detected, but it does show unknown instead of clear.

![Screenshot_20220207-212712_Home Assistant.png](https://user-images.githubusercontent.com/82621264/152918145-999efe1d-16a1-482e-9ec3-f0f6171be5b6.png)
