### ISSUE TITLE
Keypad Not Showing Up

### ISSUE THREAD

**Issue by ebotty** [natekspencer/hacs-vivint#42]
I can't seem to get the keypad in the Lovelace Alarm Card to show up with my Vivint alarm_control_panel.  I tried adding "show_keypad: true" to the card, but no luck. I also tried editing "alarm_control_panel.py", but I clearly don't know what I'm doing because I broke it and had to reinstall.

**Comment by natekspencer** [comment]
Keypad entry is not supported via this integration. The API uses the credentials to sign in as a single user so code entry is unavailable, similar to the Vivint app functionality.

**Comment by ebotty** [comment]
Got it. That makes sense. Thank you
