### ISSUE TITLE
vivint integration issues with 2022.4

### ISSUE THREAD

**Issue by scard15angel** [natekspencer/hacs-vivint#45]
I have just upgraded my HA run on ubuntu to 20.04.4 and when i try and add the latest version of the vivint integration everything runs smoothly until i try and install the repo, then it just disappears. please advise?

## System Health

version | core-2022.4.2
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.9
os_name | Linux
os_version | 5.13.0-39-generic
arch | x86_64
timezone | America/Chicago

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4668
Installed Version | 1.15.2
Stage | running
Available Repositories | 1027
Installed Repositories | 11

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | April 27, 2022, 7:00 PM
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | true
remote_server | us-east-1-1.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Ubuntu 20.04.4 LTS
-- | --
update_channel | stable
supervisor_version | supervisor-2022.04.0
docker_version | 20.10.14
disk_total | 233.2 GB
disk_used | 24.7 GB
healthy | true
supported | failed to load: Unsupported
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.3.0), File editor (5.3.3), Google Assistant SDK (2.5.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 3
views | 6
mode | storage

</details>

**Comment by natekspencer** [comment]
What do you mean by disappears? Does your system become unstable? Or you just can't find the Vivint integration?
