### ISSUE TITLE
RTSP Errors

### ISSUE THREAD

**Issue by kksligh** [natekspencer/hacs-vivint#47]
I'm getting the following error constantly in my logs using the RTSP urls for my cameras.  I recently switched my HA to a Intel NUC which may have caused this but I dont know how to get it to stop.  I have all the latest updates for HA installed and the strange thing is, the video streams work in my dashboards, so I'm not sure why this error is constantly occurring.

Logger: homeassistant.components.stream.stream.camera.kids_bedroom_camera_vivint
Source: components/stream/__init__.py:347
Integration: Stream ([documentation](https://www.home-assistant.io/integrations/stream), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+stream%22))
First occurred: 11:17:41 AM (2 occurrences)
Last logged: 11:17:58 AM

    Error from stream worker: Stream ended; no additional packets
    Error from stream worker: Error opening stream (INVALIDDATA, Invalid data found when processing input) rtsp://****:****@XXXXXXXX:8554/Video-39

2022-04-20 11:17:41 ERROR (stream_worker) [homeassistant.components.stream.stream.camera.kids_bedroom_camera_vivint] Error from stream worker: Stream ended; no additional packets

2022-04-20 11:17:58 ERROR (stream_worker) [homeassistant.components.stream.stream.camera.kids_bedroom_camera_vivint] Error from stream worker: Error opening stream (INVALIDDATA, Invalid data found when processing input) rtsp://****:****@XXXXXXXX:8554/Video-39

**NOTE: I removed IP address info above.**

**Comment by natekspencer** [comment]
Unfortunately this is an issue with the stream component. This component simply makes the Vivint camera's RTSP url available to it. Everything else from that is handled by the camera and stream components and related to issues with those and or networking hiccups on data from the camera.
