### ISSUE TITLE
HA log reporting: "... deprecated `async_get_registry` to access device registry... "

### ISSUE THREAD

**Issue by connwell** [natekspencer/hacs-vivint#50]
I'm not sure if this is the correct way to report this, so apologies if it's not.
Btw, thank you for the work on the Vivint integration! It is fantastic and I am super happy with it!

I saw the following entry in my log and the HA log suggested that I let the developer know about it, so here it is:

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:103
First occurred: June 5, 2022, 22:07:11 (2 occurrences)
Last logged: June 5, 2022, 22:32:56

Detected integration that uses deprecated `async_get_registry` to access device registry, use async_get instead. Please report issue to the custom component author for vivint using this method at custom_components/vivint/__init__.py, line 65: dev_reg = await device_registry.async_get_registry(hass)
Detected integration that uses deprecated `async_get_registry` to access device registry, use async_get instead. Please report issue to the custom component author for vivint using this method at custom_components/vivint/device_trigger.py, line 34: await hass.helpers.device_registry.async_get_registry()

**Comment by Bobbyiv** [comment]
I have also seen this error in my logs.
