### ISSUE TITLE
No Doorbell Functionality in HomeKit

### ISSUE THREAD

**Issue by ripple7511** [natekspencer/hacs-vivint#56]
First off-- THANK YOU for this incredible plugin. I recently switched from Homebridge to Home Assistant so perhaps I'm missing something? When I'm adding exposing Vivint devices from Home Assistant to HomeKit, the camera isn't recognized as a doorbell, so I'm not able to get doorbell notifications on my HomePods anymore. Is there a trick that I'm missing?

**Comment by natekspencer** [comment]
I don't use HomeKit, but it looks like you can associate the camera's motion binary sensor to be able to get that functionality: https://www.home-assistant.io/integrations/homekit/#camera-motion-notifications

**Comment by ripple7511** [comment]
Do you know if Home Assistant recognizes the doorbell press? Is there an automation port we can specify for HA to listen to in order to get that notification?

**Comment by natekspencer** [comment]
Yes, there is an event that gets fired for doorbells. It is set up as both a device trigger and an event.
