### ISSUE TITLE
No audio with doorbell

### ISSUE THREAD

**Issue by ripple7511** [natekspencer/hacs-vivint#57]
When I'm viewing the Vivint Doorbell camera via the Home Assistant interface, no audio plays. Is this expected?

**Comment by natekspencer** [comment]
The default card in Home Assistant doesn't support audio from the Vivint streams. There is a [webrtc](https://github.com/AlexxIT/WebRTC/) integration that allows this. It is currently broken in the newest HA releases at the moment though.

**Comment by natekspencer** [comment]
A fix was just merged (https://github.com/AlexxIT/WebRTC/pull/320#issuecomment-1180888344) so pending the release, it should be fixed.
