### ISSUE TITLE
Initial configuration error

### ISSUE THREAD

**Issue by pardu21** [natekspencer/hacs-vivint#59]
Hi, and thank you so much for this integration. I can't wait to use it. 

I've run into a few issues configuring this integration, though.

Here is my current HA version info
Home Assistant 2022.7.7
Supervisor 2022.07.0
Operating System 8.4
Frontend 20220707.1 - **latest**

Here is my current HACS version
Integration version: | 1.26.2
Frontend version: | 20220714083628
Repositories: | 1071
Downloaded repositories: | 3

Here are the steps I ran through
_Using HACS (see https://hacs.xyz/ for installation instructions if you do not already have it installed):
From within Home Assistant, click on the link to HACS
Click on Integrations
Click on the vertical ellipsis in the top right and select Custom repositories.
Enter the URL for this repository in the section that says Add custom repository URL and select Integration in the Category dropdown list
Click the ADD button
Close the Custom repositories window_

**You should now be able to see the Vivint card on the HACS Integrations page. Click on INSTALL and proceed with the installation instructions.** I didn't get an INSTALL button here just a download, so I did that.

_Restart your Home Assistant instance and then proceed to the Configuration section below._

The configuration went fine until I ran into the following error after signing into vivint and adding my password.

![image](https://user-images.githubusercontent.com/92659694/182035775-10ae8c5f-5a7e-4ac3-95ab-ada3d5bc1676.png)

I clicked to check the logs and see the following error. I'm unsure how to troubleshoot this and would greatly appreciate any help you can provide. Thank you.

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/vivint/hub.py:94
Integration: Vivint (documentation, issues)
First occurred: 9:42:43 AM (3 occurrences)
Last logged: 9:44:31 AM

Error setting up entry user@gmail.com(_changed to dummy email for this post_) for vivint
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 353, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/vivint/__init__.py", line 59, in async_setup_entry
    await hub.login(load_devices=True, subscribe_for_realtime_updates=True)
  File "/config/custom_components/vivint/hub.py", line 94, in login
    await self.account.connect(
  File "/usr/local/lib/python3.10/site-packages/vivintpy/account.py", line 72, in connect
    await self.subscribe_for_realtime_updates(authuser_data)
  File "/usr/local/lib/python3.10/site-packages/vivintpy/account.py", line 167, in subscribe_for_realtime_updates
    self.__pubnub = PubNubAsyncio(pnconfig)
  File "/usr/local/lib/python3.10/site-packages/pubnub/pubnub_asyncio.py", line 38, in __init__
    super(PubNubAsyncio, self).__init__(config)
  File "/usr/local/lib/python3.10/site-packages/pubnub/pubnub_core.py", line 97, in __init__
    @abstractmethod
  File "/usr/local/lib/python3.10/site-packages/pubnub/pnconfiguration.py", line 39, in validate
    assert self.uuid is None or isinstance(self.uuid, str)
  File "/usr/local/lib/python3.10/site-packages/pubnub/pnconfiguration.py", line 42, in validate_not_empty_string
    self.uuid = utils.uuid()
AssertionError: UUID missing or invalid type

**Comment by natekspencer** [comment]
Do you mind sharing what other integrations you have installed in Home Assistant? This particular error is from a new version of pubnub, but the underlying package for this integration restricts the version that should be installed. So I'm curious if you have another integration installed that requires a later version, thus conflicting with this integration.

**Comment by pardu21** [comment]
Thank you for your reply. I have the following integrations:
August
Denon AVR network receivers
Denon HEOS
Dialogflow Webhook
Ecobee
Google Cast
HACS
Home Assistant Supervisor
HomeKit Controller
Meteorologisk Institutte
MQTT
Philips Hue
Sun
Synology DSM
TP-Link Kasa Smart 
Unifi Network
WiZ

**Comment by natekspencer** [comment]
August uses pubnub as well it looks like. It requires the same minimum version, but doesn't restrict higher versions like the vivintpy library.  Since you likely installed that first, it probably downloaded pubnub version 6.x. I think if you uninstalled both Vivint and August, restarted Home Assistant, then installed Vivint first, followed by August, both would work fine together until I have a chance to update the vivintpy library to support pubnub>=6.x

**Comment by pardu21** [comment]
Sounds good. I'll give that a shot. Thank you.

**Comment by pardu21** [comment]
I believe that did it. Thank you so much for your help. I do have one last question. Do you know if you can control the Kwikset door locks from home assistant(ie lock and unlock)?

**Comment by natekspencer** [comment]
Awesome. And yes, locks are controllable
