### ISSUE TITLE
Support for panels to arm/disarm?

### ISSUE THREAD

**Issue by vaparr** [natekspencer/hacs-vivint#60]
I was recently using the homebridge vivint module from:

https://github.com/balansse/homebridge-vivint

And it supports my panel, and allows me to arm/disarm, which is extremely useful in my routines.  Is this possible in the HA intregration?

**Comment by natekspencer** [comment]
Yup, it is!

**Comment by vaparr** [comment]
Thanks. I found it.. I can finally get rid of home bridge! Thank you so much for this integration!
