### ISSUE TITLE
Integration Becoming Unavailable

### ISSUE THREAD

**Issue by kksligh** [natekspencer/hacs-vivint#62]
I've been using this integration for some time and have suddenly experienced a lot of instability in the last week or so.  Below is the error I am getting in the logs:

`This error originated from a custom integration.

Logger: custom_components.vivint.hub
Source: helpers/update_coordinator.py:151
Integration: Vivint (documentation, issues)
First occurred: 7:13:16 PM (1 occurrences)
Last logged: 7:13:16 PM

Error requesting vivint data: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://www.vivintsky.com/api/authuser')`

Can you take a look?  When this error shows up, my entire list of devices go unavailable.

**Comment by natekspencer** [comment]
It's likely the Vivint API having issues. But I should account for it and not completely error out when this happens

**Comment by kksligh** [comment]
More errors...

Logger: vivintpy.pubnub
Source: runner.py:119 
First occurred: 8:04:46 PM (3 occurrences) 
Last logged: 10:18:54 PM

PubNub status error - operation: SUBSCRIBE, category: UNKNOWN, error: [Errno 104] Connection reset by peer
PubNub status error - operation: HEARTBEAT, category: UNKNOWN, error: Cannot connect to host ps.pndsn.com:443 ssl:default [Try again]


Logger: pubnub
Source: runner.py:119 
First occurred: 8:04:46 PM (5 occurrences) 
Last logged: 10:18:54 PM

session.request exception: [Errno 104] Connection reset by peer
Exception in subscribe loop: [Errno 104] Connection reset by peer
session.request exception: Cannot connect to host ps.pndsn.com:443 ssl:default [Try again]

**Comment by kksligh** [comment]
I think it's on my end. Seeing some static IP weirdness going on. Closing for now.
