### ISSUE TITLE
Can't Authenticate

### ISSUE THREAD

**Issue by ksignorini** [natekspencer/hacs-vivint#63]
I changed my Vivint password and can log into both vivint.com and vivintsky.com using it.

Since changing my password, this Vivint integration is showing in red and requires authentication ("RECONFIGURE").

My Vivint username and new password don't work. It continues to ask for authentication. ("Invalid authentication")

**Comment by ksignorini** [comment]
Well. It turns out that when you change your Vivint password, you need to Remove and re-Add the integration so you can handle the MFA code.

Is it possible to put that same process (username/password/MFA) into the RECONFIGURE process so the entire integration does not need to be reinstalled each time after a password change, or is this something inherent in HA?

**Comment by HandyRandy512** [comment]
> Well. It turns out that when you change your Vivint password, you need to Remove and re-Add the integration so you can handle the MFA code.
> 
> Is it possible to put that same process (username/password/MFA) into the RECONFIGURE process so the entire integration does not need to be reinstalled each time after a password change, or is this something inherent in HA?

I'm trying to do this but I'm stuck in what appears to be an infinite download, after I click the "download" button, the symbol just keeps spinning.

**Comment by HandyRandy512** [comment]
> Well. It turns out that when you change your Vivint password, you need to Remove and re-Add the integration so you can handle the MFA code.
> 
> Is it possible to put that same process (username/password/MFA) into the RECONFIGURE process so the entire integration does not need to be reinstalled each time after a password change, or is this something inherent in HA?

Trying manual mode. Stuck at MFA code

![image](https://user-images.githubusercontent.com/95545586/206741209-1b69060d-c9a7-4f0e-b4ad-103b46199b0d.png)

**Comment by natekspencer** [comment]
Can you provide the logs? Unfortunately the image doesn't give much insight.
