### ISSUE TITLE
MFA Failing

### ISSUE THREAD

**Issue by HandyRandy512** [natekspencer/hacs-vivint#64]
After login credentials, I'm asked to enter the "MFA code" which I assume is the 6 digit (2fa) received from authenticator app. 

![Screenshot 2022-12-09 105101](https://user-images.githubusercontent.com/95545586/206756769-b572af5a-5145-44ac-a5d4-0ee8016fc873.jpg)

This error originated from a custom integration.

Logger: custom_components.vivint.config_flow
Source: custom_components/vivint/config_flow.py:133
Integration: vivint (documentation, issues)
First occurred: 10:42:55 AM (3 occurrences)
Last logged: 12:11:36 PM

403, message='Forbidden', url=URL('https://www.vivintsky.com/platform-user-api/v0/platformusers/2fa/validate')

**Comment by natekspencer** [comment]
You are probably getting an "invalid code" error, but I've release a new version (2022.12.0) to hopefully display some better error messages that come back. Please update and try again and see if anything changes.

**Comment by HandyRandy512** [comment]
> You are probably getting an "invalid code" error, but I've release a new version (2022.12.0) to hopefully display some better error messages that come back. Please update and try again and see if anything changes.

invalid field Code: value ' 912158' must be a string conforming to regex "^\\d{6}$"

The MFA code is the 6 digit code generated by my authorization app?

**Comment by natekspencer** [comment]
It looks like you have a space in front of it

**Comment by HandyRandy512** [comment]
> It looks like you have a space in front of it

New error: Code is not valid

I just tried putting the code right as it was generated. Maybe taking to long to go through. I dont get a response for about 1 minute.

**Comment by HandyRandy512** [comment]
> > It looks like you have a space in front of it
> 
> New error: Code is not valid
> 
> I just tried putting the code right as it was generated. Maybe taking to long to go through. I dont get a response for about 1 minute.

Still got a "Code is not valid". Seems to be taking to long.

**Comment by natekspencer** [comment]
It sounds like it might have timed out then as it shouldn't take near that long for a response.

**Comment by HandyRandy512** [comment]
> It sounds like it might have timed out then as it shouldn't take near that long for a response.

I'm having issues with HACS updates (ie card mod wont update) and downloads timing out. Maybe related. I'll upate any fixes I find.

**Comment by HandyRandy512** [comment]
> 

Resolve all issues by turning off the IPv6 option in my new mesh routers. Thanks
