### ISSUE TITLE
Integration could not be setup

### ISSUE THREAD

**Issue by mat1583** [natekspencer/hacs-vivint#66]
After updating to HA 12.3 and Vivint 12.0, the Vivint integration is no longer working and can't be setup. This is what I'm seeing on the logs. 

Log Details (ERROR)
Logger: homeassistant.util.package
Source: util/package.py:98
First occurred: 5:35:17 AM (3 occurrences)
Last logged: 5:35:35 AM

Unable to install package vivintpy==2022.12.0: ERROR: Cannot install vivintpy==2022.12.0 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip available: 22.3 -> 22.3.1 [notice] To update, run: pip install --upgrade pip

**Comment by mat1583** [comment]
Downgrading to previous version fixes the issue.

**Comment by mlittle408** [comment]
How do you downgrade. I am having the same problem. Thanks!

**Comment by mlittle408** [comment]
I figured it out. thx

**Comment by natekspencer** [comment]
This was caused because [HA downgraded aiohttp to 3.8.1 after they noticed some issues](https://github.com/home-assistant/core/pull/83795). I'm rolling out a fix shortly.

**Comment by natekspencer** [comment]
Resolved with 2022.12.1

**Comment by mat1583** [comment]
Confirmed working again. Thanks, Nate!
