### ISSUE TITLE
Unknown device type value: lgit_poe_wifi_device

### ISSUE THREAD

**Issue by mat1583** [natekspencer/hacs-vivint#68]
After 12.1 got things working again, I'm seeing this error on HA restart:

This error originated from a custom integration.

Logger: vivintpy.enums
Source: custom_components/vivint/hub.py:94
Integration: Vivint (documentation, issues)
First occurred: 10:56:28 AM (1 occurrences)
Last logged: 10:56:28 AM

Unknown device type value: lgit_poe_wifi_device

**Comment by natekspencer** [comment]
I should probably change those to warnings rather than errors. It shouldn't cause any issues though. I also don't think it's a relevant security device for HA (looks like a Power over Ethernet device?)

**Comment by mat1583** [comment]
My best guess is that it's their POE bridge for the outdoor camera I have.

**Comment by natekspencer** [comment]
This is address in 2022.12.2
