### ISSUE TITLE
Deprecation warning in logs

### ISSUE THREAD

**Issue by cryptk** [natekspencer/hacs-vivint#70]
Hello, in my system logs, I have the following deprecation warning:

```
This error originated from a custom integration.

Logger: vivintpy.utils
Source: custom_components/vivint/alarm_control_panel.py:60
Integration: Vivint (documentation, issues)
First occurred: 8:21:14 PM (41 occurrences)
Last logged: 9:46:14 PM

method get_armed_state has been deprecated in favor of property state, the alias will be removed in the future
```

Figured I should let you know

**Comment by natekspencer** [comment]
Resolved in 2022.12.3

**Comment by cryptk** [comment]
@natekspencer it looks like you accidentally tagged that as 2021 instead of 2022 so HACS isn't offering it as an update because the version number appears to be older

**Comment by natekspencer** [comment]
> @natekspencer it looks like you accidentally tagged that as 2021 instead of 2022 so HACS isn't offering it as an update because the version number appears to be older

🤦🏻‍♂️
Try again now
