### ISSUE TITLE
Re-authenticate every few days

### ISSUE THREAD

**Issue by motoxprnce** [natekspencer/hacs-vivint#73]
The integration seems to want to re-authenticate every few days, so i will be left without my system showing until i uninstall and re-install the integration. Is there a way to make it not try to authenticate so often?

**Comment by natekspencer** [comment]
I've not seen this issue and mine has been running for quite some time. Can you see if there are any debug logs associated with it?

**Comment by motoxprnce** [comment]
It tells me "invalid credentials" but i input the correct credentials, it is like it logs itself out and then trys to log back in but it lost the credentials.

![2023-01-03 20_48_40-Window](https://user-images.githubusercontent.com/98284726/210486532-a166fbf2-32a1-4680-9526-f1028b43a208.jpg)

**Comment by markmanxp** [comment]
Yes, I'm seeing the same issue this morning as nitixornce is sharing with his screenshot.  I had applied the latest HA update Wednesday FWIW>
