### ISSUE TITLE
Can't show keypad on alarm card

### ISSUE THREAD

**Issue by RichMicek** [natekspencer/hacs-vivint#74]
Not sure if this is just to do using Vivint or some other issue

**Comment by natekspencer** [comment]
This integration mimics the Vivint app which doesn't require a code as it assumes the identity of the logged-in user.

**Comment by RichMicek** [comment]
Got it. Thanks for the quick response.  I was hoping to add the disarm
function to a dashboard I created mounted on the wall but I will just leave
it off
