### ISSUE TITLE
async_setup_platforms will fail in vs 2023.3

### ISSUE THREAD

**Issue by mat1583** [natekspencer/hacs-vivint#76]
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:77
First occurred: 6:53:37 AM (1 occurrences)
Last logged: 6:53:37 AM

Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for vivint using this method at custom_components/vivint/__init__.py, line 129: hass.config_entries.async_setup_platforms(entry, PLATFORMS)

**Comment by natekspencer** [comment]
Fixed in 2023.2.1
