### ISSUE TITLE
Expose doorbell button press as a separate entity

### ISSUE THREAD

**Issue by aacentric** [natekspencer/hacs-vivint#80]
Is it possible to expose the Vivint doorbell camera button as a separate entity in Home Assistant?  I currently have my doorbell and other Vivint cameras running through Scrypted into HomeKit which is lighting fast, but there's no way to detect the doorbell button press (uses local RTSP stream only) so I don't have any notifications from that.  Would be awesome to have the doorbell button press as a standalone entity so I can get notifications into my HA setup and use that for other stuff.

Would be great if do-able, thank you so much for your work on this!

**Comment by natekspencer** [comment]
The doorbell button press is exposed via an event already.

**Comment by Kahros** [comment]
Hello!  I'm responding to this thread as I am looking for doorbell functionality but it's non existent.  Maybe this is a thing with the newer doorbells?

Mine only shows the motion sensor and the camera feed.

![Screenshot_2023-03-22-05-12-05-43_c3a231c25ed346e59462e84656a70e50](https://user-images.githubusercontent.com/96829575/227004302-40d54829-a793-47a1-bfc0-d41265c5c556.jpg)

**Comment by natekspencer** [comment]
You won't see a sensor for the doorbell ding event. But you can trigger off of it via automations.

**Comment by Kahros** [comment]
> You won't see a sensor for the doorbell ding event. But you can trigger off of it via automations.

Would the event trigger to use be "DOORBELL_DING"?

**Comment by natekspencer** [comment]
Yeah, if you select `Device` as the trigger, then choose your doorbell, you should see a `Motion detected` or `Doorbell pressed` event.
<img width="1036" alt="Screenshot 2023-03-22 at 12 57 13" src="https://user-images.githubusercontent.com/3792831/227008915-9c0042a0-23bf-449e-bee7-bd95942927c3.png">

**Comment by Kahros** [comment]
> Yeah, if you select `Device` as the trigger, then choose your doorbell, you should see a `Motion detected` or `Doorbell pressed` event. <img alt="Screenshot 2023-03-22 at 12 57 13" width="1036" src="https://user-images.githubusercontent.com/3792831/227008915-9c0042a0-23bf-449e-bee7-bd95942927c3.png">

Got it!  Thanks for leading the donkey to water.  No idea how I missed that!
