### ISSUE TITLE
Alarm Keypad Missing

### ISSUE THREAD

**Issue by ikeurb** [natekspencer/hacs-vivint#88]
With the mushroom alarm card or the default HA alarm card, the keypad is not appearing. I am able to disarm the alarm by simply pressing the disarm button on the alarm card. This seems like a security loophole. I should be prompted for the disarm code when disarming the alarm system.

**Comment by ikeurb** [comment]
It would be nice if possible, to have a parameter to disable disarming.  Basically a configuration setting to only enable the ability to allow arming from the HA Integration.

**Comment by natekspencer** [comment]
> It would be nice if possible, to have a parameter to disable disarming. Basically a configuration setting to only enable the ability to allow arming from the HA Integration.

This seems pretty niche to disable only the disarming of a an alarm panel. I could potentially see a setting that disables disarming the panel, unlocking doors and opening garages potentially if there is enough interest.

Perhaps if you explained your use case more though. Are you trying to prevent other invited HA users from disarming your system? Or trying to prevent someone who has hacked into your HA environment and then being able to disarm your system and gain access to your home, etc?

**Comment by ikeurb** [comment]
I have a couple HA Lovelace Dashboard Panels in the home. The concern is if there is an intruder, they could easily disarm the alarm using the HA panel.

I just dont want the disarm function being present on the HA panels with no alarm code keypad being offered as that does not provide the level of security I am looking for.

Looking at previous issues that were reported for this integration, another user stated he would just remove the alarm card from lovelace so this concern wasnt possible.

I would still like to use the alarm card to arm my system when needed through HA Lovelace alarm card. Since HACS Vivint Integration does not present the keypad, I would then disarm Vivint using another method such as the native Vivint panel.

**Comment by natekspencer** [comment]
@ikeurb I decided to add a configuration option for a disarm code. You can set this to any length number, which will then require that code to disarm the alarm and will show the keypad in HA.
